#!/bin/bash

if [ -z "$1" ]; then
cat <<EOU
Compute myelin maps for a FreeSurfer subject if the subject
has been processed using either T2 or FLAIR images.
This requires having both FSL and FreeSurfer installed.

Can also compute gray/white contrast. This requires only FreeSurfer.

Usage: melina -s <subjid> [options]

-s <subjid>   : Subject (already processed with recon-all).
-f <projfrac> : Fractional projection along normal. Can be between
                0 and 1, with 0 being white and 1 pial. Can take
                negative values (in which case it goes deep into
                the white matter.
                Default is 0.5. If supplied, the output file will
                contain the value in the filename.
                More than one -f can be supploed.
-d <distance> : Same as -f, but uses absolute distance (in mm)
                from the white surface.
-c            : Compute also the gray/white contrast.

_____________________________________
Anderson M. Winkler
Hospital Israelita Albert Einstein
Aug/2017 (first version)
Jun/2025 (this version)
http://brainder.org
EOU
exit 1
fi

# Check and accept the input arguments
subj=""
PF_LIST=""
PD_LIST=""
DOGWC=false
while getopts 's:f:d:c' OPTION
do
  case ${OPTION} in
    s) subj=${OPTARG} ;;
    f) PF_LIST="${PF_LIST} ${OPTARG}" ;;
    d) PD_LIST="${PD_LIST} ${OPTARG}" ;;
    c) DOGWC=true
  esac
done
if [[ ${PF_LIST} == "" ]] && [[ ${PD_LIST} == "" ]] ; then
  PF_LIST=0.5
fi
if   [[ -f ${SUBJECTS_DIR}/${subj}/mri/T2.prenorm.mgz ]] ; then
   TYPE=T2
elif [[ -f ${SUBJECTS_DIR}/${subj}/mri/FLAIR.prenorm.mgz ]] ; then
   TYPE=FLAIR
else
   TYPE=""
fi
if [[ -z ${TYPE} ]] ; then
   if [[ ${DOGWC} ]] ; then
      echo "Warning! Neither of the files below exist. At least one must be present to compute a myelin surrogate:"
      echo "- ${SUBJECTS_DIR}/${subj}/mri/T2.prenorm.mgz"
      echo "- ${SUBJECTS_DIR}/${subj}/mri/FLAIR.prenorm.mgz"
      echo "Skipping"
   else
      echo "Error! Neither of the files below exist. At least one must be present to compute a myelin surrogate:"
      echo "- ${SUBJECTS_DIR}/${subj}/mri/T2.prenorm.mgz"
      echo "- ${SUBJECTS_DIR}/${subj}/mri/FLAIR.prenorm.mgz"
      echo "Stopping."
      exit 1
   fi
fi

# Create directory to store outputs
mkdir -p ${SUBJECTS_DIR}/${subj}/after/melina

if [[ ${TYPE} == "T2" ]] || [[ ${TYPE} == "FLAIR" ]] ; then

   # Find out whether recon-all used "-hires" or not
   if [[ $(grep --regexp="recon-all.*-hires" ${SUBJECTS_DIR}/${subj}/scripts/recon-all.log|wc -l) -eq 0 ]] ; then
      CONFORM_FLAG="--conform"
   else
      CONFORM_FLAG="--conform_min"
   fi

   # Conform rawavg, but without changing the datatype
   ${FREESURFER_HOME}/bin/mri_convert \
      ${SUBJECTS_DIR}/${subj}/mri/rawavg.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.mgz ${CONFORM_FLAG} --nochange

   # Compute the myelin surrogate
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.mgz div \
      ${SUBJECTS_DIR}/${subj}/mri/${TYPE}.prenorm.mgz \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/myelin.mgz

   # Convert orig_nochange to NIFTI so we can use FAST
   ${FREESURFER_HOME}/bin/mri_convert -it mgz -ot nii \
      -i ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.mgz \
      -o ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.nii.gz

   # Convert aseg to NIFTI, dilate just a bit, so that we can use later for
   # masking before doing FAST
   ${FREESURFER_HOME}/bin/mri_convert -it mgz -ot nii \
      -i ${SUBJECTS_DIR}/${subj}/mri/aparc+aseg.mgz \
      -o ${SUBJECTS_DIR}/${subj}/after/melina/aparc+aseg.nii.gz
   echo "Running fslmaths twice (for dilation and for masking)"
   ${FSLDIR}/bin/fslmaths \
      ${SUBJECTS_DIR}/${subj}/after/melina/aparc+aseg.nii.gz \
      -bin -kernel 3D -dilM \
      ${SUBJECTS_DIR}/${subj}/after/melina/aparc+aseg_mask_dilated.nii.gz
   
   # Mask the orig_nochange, so we can use FAST properly
   ${FSLDIR}/bin/fslmaths \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.nii.gz -mul \
      ${SUBJECTS_DIR}/${subj}/after/melina/aparc+aseg_mask_dilated.nii.gz \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked.nii.gz

   # Segment using FAST, and convert back to MGZ
   echo "Running FAST."
   ${FSLDIR}/bin/fast ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked.nii.gz
   for p in 1 2 ; do
      ${FREESURFER_HOME}/bin/mri_convert -it nii -ot mgz \
      -i ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_${p}.nii.gz \
      -o ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_${p}.mgz
   done

   # Sum GM and WM fractions
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_1.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_2.mgz \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_1+2.mgz

   # Apply the mask to the myelin surrogate
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/myelin.mgz mul \
      ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_1+2.mgz \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/myelin_pvc.mgz

   # Now that PVC has been applied, let's also obtain the average value for GM, WM and CSF
   # for this participant. We only want the "best" voxels, so let's erode a bit.
   ${FREESURFER_HOME}/bin/mri_convert -it mgz -ot nii \
      -i ${SUBJECTS_DIR}/${subj}/after/melina/myelin.mgz \
      -o ${SUBJECTS_DIR}/${subj}/after/melina/myelin.nii.gz
   Mstr=""
   for p in 0 1 2 ; do
      ${FSLDIR}/bin/fslmaths \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_${p}.nii.gz \
         -bin -kernel boxv 3 -ero \
         -mul \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_${p}.nii.gz \
         -mul \
         ${SUBJECTS_DIR}/${subj}/after/melina/myelin.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/myelin_pve_${p}_eroded.nii.gz
      M=$(${FSLDIR}/bin/fslstats ${SUBJECTS_DIR}/${subj}/after/melina/myelin_pve_${p}_eroded.nii.gz -M)
      Mstr="${Mstr}${M}"
   done
   echo "${Mstr}" | sed 's/\ $//g' | sed 's/\ /\,/g' > ${SUBJECTS_DIR}/${subj}/after/melina/tissue_intensities.csv

   # Remove unused files
   rm -f ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.mgz \
         ${SUBJECTS_DIR}/${subj}/after/melina/aparc+aseg.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/aparc+aseg_mask_dilated.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_seg.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_?.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pveseg.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_mixeltype.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_?.mgz \
         ${SUBJECTS_DIR}/${subj}/after/melina/orig_nochange_masked_pve_1+2.mgz \
         ${SUBJECTS_DIR}/${subj}/after/melina/myelin.nii.gz \
         ${SUBJECTS_DIR}/${subj}/after/melina/myelin_pve_?_eroded.nii.gz
          
   # Project to the surface, using fraction of distance between white (0) and pial (1)
   if [[ ${PF_LIST} != "" ]] ; then
      for pf in ${PF_LIST} ; do
         pfstr="f_${pf}"
         for h in lh rh ; do
            ${FREESURFER_HOME}/bin/mri_vol2surf \
               --mov ${SUBJECTS_DIR}/${subj}/after/melina/myelin.mgz \
               --regheader ${subj} --projfrac ${pf} --interp trilinear \
               --hemi ${h} --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pfstr}.mgz
            ${FREESURFER_HOME}/bin/mris_convert -c \
               ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pfstr}.mgz \
               ${SUBJECTS_DIR}/${subj}/surf/${h}.white \
               ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pfstr}
            rm -f ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pfstr}.mgz
         done
      done
   fi
   
   # Project to the surface, using a distance from the white.
   if [[ ${PD_LIST} != "" ]] ; then
      for pd in ${PD_LIST} ; do
         pdstr="d_${pd}mm"
         for h in lh rh ; do
            ${FREESURFER_HOME}/bin/mri_vol2surf \
               --mov ${SUBJECTS_DIR}/${subj}/after/melina/myelin.mgz \
               --regheader ${subj} --projdist ${pd} --interp trilinear \
               --hemi ${h} --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pdstr}.mgz
            ${FREESURFER_HOME}/bin/mris_convert -c \
               ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pdstr}.mgz \
               ${SUBJECTS_DIR}/${subj}/surf/${h}.white \
               ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pdstr}
            rm -f ${SUBJECTS_DIR}/${subj}/after/melina/${h}.myelin.${pdstr}.mgz
         done
      done
   fi
fi

# Compute the GWC, for each hemisphere separately
if [[ ${DOGWC} ]] ; then
   for h in lh rh ; do

   # Project to the surface, using fraction of distance between white (0) and pial (1)
   PF_LIST="0.1 0.2 0.3 0.4 0.5 0.6"
   for pf in ${PF_LIST} ; do
      [[ $(echo ${PF_LIST}|wc -w) -gt 1 ]] && pfstr="f_${pf}" || pfstr=""
      ${FREESURFER_HOME}/bin/mri_vol2surf \
         --mov ${SUBJECTS_DIR}/${subj}/mri/nu.mgz \
         --regheader ${subj} --projfrac ${pf} --interp trilinear \
         --hemi ${h} --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.${pfstr}.mgz
   done

   # Project to the surface, using a distance from the white.
   PD_LIST="0.15 0.30 0.45 0.60 0.75 0.90 1.05 1.20 1.35 1.50"
   for pd in ${PD_LIST} ; do
      [[ $(echo ${PD_LIST}|wc -w) -gt 1 ]] && pdstr="d_${pd}mm" || pdstr=""
      ${FREESURFER_HOME}/bin/mri_vol2surf \
         --mov ${SUBJECTS_DIR}/${subj}/mri/nu.mgz \
         --regheader ${subj} --projdist -${pd} --interp trilinear \
         --hemi ${h} --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.${pdstr}.mgz
   done

   # Average the layers, then compute the difference and normalize by the mean
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.1.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.2.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.3.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.4.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.5.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.6.mgz div 6 \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_avg.mgz
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.15mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.30mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.45mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.60mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.75mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.90mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.05mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.20mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.35mm.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.50mm.mgz div 10 \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_avg.mgz
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_avg.mgz sub \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_avg.mgz mul 100 \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.diff.mgz
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_avg.mgz add \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_avg.mgz div 2 \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.mean.mgz
   ${FREESURFER_HOME}/bin/fscalc \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.diff.mgz div \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.mean.mgz \
      --o ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.mgz
   ${FREESURFER_HOME}/bin/mris_convert -c \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.mgz \
      ${SUBJECTS_DIR}/${subj}/surf/${h}.white \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc

   # Remove unused files
   rm -f \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.1.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.2.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.3.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.4.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.5.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_0.6.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.15mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.30mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.45mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.60mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.75mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_0.90mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.05mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.20mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.35mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_1.50mm.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.graylayer.f_avg.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.whitelayer.d_avg.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.diff.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.mean.mgz \
      ${SUBJECTS_DIR}/${subj}/after/melina/${h}.gwc.mgz
   done # for each hemi
fi
