#!/bin/bash

# Print usage if no argument is given
if [ -z "$1" ]; then
cat <<EOU
Linearly aligns a number of images to a target and
computes the average.

Usage:
stereomc -i image1.nii.gz -i image2.nii.gz -i ... \\
         -t target.nii.gz -o outputimage.nii.gz -k

Options:
-i <image list> : Input images (at least 2).
-t <target>     : Target for registration. It can be one
                  of the inputs or another image.
-o <output>     : Output image, the average of all.
-d              : If specified, keep temporary files,
                  useful for debugging.

Requirements:
FreeSurfer and FSL must be installed and configured.

Reference:
Kochunov P et al. Retrospective motion correction 
protocol for high-resolution anatomical MRI.
Hum Brain Mapp. 2006 Dec;27(12):957-62.

________________________________________
Anderson M. Winkler
Institute of Living / Yale University
August/2010 (first version)
July/2025 (this version)
EOU
exit
fi

# Check for FSL and FreeSurfer
if [ -z "${FSLDIR}" ] ; then
   echo "FSL not found. Please, configure FSLDIR correctly."
   exit 1 ;
fi
if [ -z "${FREESURFER_HOME}" ] ; then
   echo "FreeSurfer not found. Please, configure FREESURFER_HOME correctly."
   exit 1 ;
fi

# Accept inputs
IMG_LIST=""
DEBUG=false
while getopts 'i:t:o:k' OPTION
do
  case ${OPTION} in
    i) IMG_LIST="${IMG_LIST} ${OPTARG}" ;;
    t) TARGET=${OPTARG} ;;
    o) OUTPUT=${OPTARG} ;;
    d) DEBUG=true ;;
  esac
done

# Output directory
OUTDIR=$(dirname ${OUTPUT})

# Print in the inputs in the screen:
echo "Input images: ${IMG_LIST}"
echo "Target image:  ${TARGET}"
echo "Average image: ${OUTPUT}"

# When parsing just 1 input, copy to the output.
if [ $(echo ${IMG_LIST}| wc -w) -eq 1 ] ; then
   ${FSLDIR}/bin/imcp ${IMG_LIST} ${OUTPUT}
   exit 0
fi

# Skull strip the target
echo "Skull stripping target ${TARGET}"
tbase=$(basename $(${FSLDIR}/bin/remove_ext ${TARGET}))
${FREESURFER_HOME}/bin/mri_synthstrip -in ${TARGET} -o ${OUTDIR}/${tbase}_brain.nii.gz

# Skull stripping and linear alignment of each image to the target
MC_LIST=""
for i in ${IMG_LIST} ; do
   echo "Aligning image ${i}"
   
   # Skull stripping
   ibase=$(basename $(${FSLDIR}/bin/remove_ext ${i}))
   ${FREESURFER_HOME}/bin/mri_synthstrip -in ${i} -o ${OUTDIR}/${ibase}_brain.nii.gz
   
   # Align with FLIRT
   ${FSLDIR}/bin/flirt -in   ${OUTDIR}/${ibase}_brain \
                       -ref  ${OUTDIR}/${tbase}_brain \
                       -out  ${OUTDIR}/${ibase}_brain_aligned \
                       -omat ${OUTDIR}/${ibase}_brain_aligned.mat \
                       -dof 6 \
                       -interp sinc
   ${FSLDIR}/bin/flirt -in   ${i} \
                       -ref  ${OUTDIR}/${tbase}_brain \
                       -out  ${OUTDIR}/${ibase}_aligned \
                       -init ${OUTDIR}/${ibase}_brain_aligned.mat \
                       -interp sinc \
                       -applyxfm
   MC_LIST="${MC_LIST} ${OUTDIR}/${ibase}_aligned"
done

# Concatenation of the aligned images
echo "Creating temporary 4D file"
tmp4dfile="4d_tmp"
${FSLDIR}/bin/fslmerge -t ${OUTDIR}/4d ${MC_LIST}

# Average of the aligned images
echo "Averaging"
${FSLDIR}/bin/fslmaths ${OUTDIR}/4d -Tmean ${OUTPUT}

# Either rename or get rid of the .mat files
if ! ${DEBUG} ; then
   rm -rf ${OUTDIR}/${tbase}_brain.nii.gz
   for i in ${IMG_LIST} ; do
      ibase=$(basename $(${FSLDIR}/bin/remove_ext ${i}))
      rm -rf ${OUTDIR}/${ibase}_brain.* \
             ${OUTDIR}/${ibase}_brain_aligned.*
   done
fi
echo "Done!"
exit
